jobs:
  - name: x86-64-windows-server-2016-container-custom-img-valid
    type: runSh
    runtime:
      architecture: x86_64
      cluster: x8664win2016custom
      container: true
    flags:
      - x86-64
      - windows-server-2016
      - windows-server-2016-custom-img
    steps:
      - IN: x86-64-trigger
      - IN: windows-server-2016-trigger
      - TASK:
          name: say-hello-world
          runtime:
            options:
              imageName: "microsoft/windowsservercore"
              imageTag: "10.0.14393.1884"
          script:
            - Write-Output "Hello world"

  - name: x86-64-windows-server-2016-container-custom-img-invalid
    type: runSh
    runtime:
      architecture: x86_64
      cluster: x8664win2016custom
      container: true
    flags:
      - x86-64
      - windows-server-2016
      - windows-server-2016-custom-img
    steps:
      - IN: x86-64-trigger
      - IN: windows-server-2016-trigger
      - TASK:
          name: should-fail-in-boot
          runtime:
            options:
              imageName: "microsoft/windowsservercore"
              imageTag: "invalid.image.tag"
          script:
            - Write-Output "Did you just use a valid image tag?"

  - name: x86-64-windows-server-2016-container-custom-img-single-valid
    type: runSh
    runtime:
      architecture: x86_64
      cluster: x8664win2016custom
      container: true
    flags:
      - x86-64
      - windows-server-2016
      - windows-server-2016-custom-img
    steps:
      - IN: x86-64-trigger
      - IN: windows-server-2016-trigger
      - TASK:
          name: single-cmd-should-work
          runtime:
            options:
              imageName: "microsoft/windowsservercore"
              imageTag: "10.0.14393.1884"
          script:
            - dir

  - name: x86-64-windows-server-2016-container-custom-img-single-invalid
    type: runSh
    runtime:
      architecture: x86_64
      cluster: x8664win2016custom
      container: true
    flags:
      - x86-64
      - windows-server-2016
      - windows-server-2016-custom-img
    steps:
      - IN: x86-64-trigger
      - IN: windows-server-2016-trigger
      - TASK:
          name: single-cmd-should-not-work
          runtime:
            options:
              imageName: "microsoft/windowsservercore"
              imageTag: "10.0.14393.1884"
          script:
            - invalidCommand

  - name: x86-64-windows-server-2016-container-custom-img-multiple-valid
    type: runSh
    runtime:
      architecture: x86_64
      cluster: x8664win2016custom
      container: true
    flags:
      - x86-64
      - windows-server-2016
      - windows-server-2016-custom-img
    steps:
      - IN: x86-64-trigger
      - IN: windows-server-2016-trigger
      - TASK:
          name: multiple-cmd-should-work
          runtime:
            options:
              imageName: "microsoft/windowsservercore"
              imageTag: "10.0.14393.1884"
          script:
            - dir
            - echo "hello world"
            - Start-Sleep -s 100
            - echo "This should not show up if job was cancelled 1"
            - echo "This should not show up if job was cancelled 2"
            - echo "This should not show up if job was cancelled 3"
            - echo "This should not show up if job was cancelled 4"
            - echo "This should not show up if job was cancelled 5"
            - echo "This should not show up if job was cancelled 6"
            - echo "This should not show up if job was cancelled 7"
            - echo "This should not show up if job was cancelled 8"
            - echo "This should not show up if job was cancelled 9"
            - echo "This should not show up if job was cancelled 10"

  - name: x86-64-windows-server-2016-container-custom-img-multiple-invalid
    type: runSh
    runtime:
      architecture: x86_64
      cluster: x8664win2016custom
      container: true
    flags:
      - x86-64
      - windows-server-2016
      - windows-server-2016-custom-img
    steps:
      - IN: x86-64-trigger
      - IN: windows-server-2016-trigger
      - TASK:
          name: multiple-cmd-should-not-work
          runtime:
            options:
              imageName: "microsoft/windowsservercore"
              imageTag: "10.0.14393.1884"
          script:
            - echo "next command will be invalid"
            - invalidCommand

  - name: x86-64-windows-server-2016-container-custom-img-multiple-error
    type: runSh
    runtime:
      architecture: x86_64
      cluster: x8664win2016custom
      container: true
    flags:
      - x86-64
      - windows-server-2016
      - windows-server-2016-custom-img
    steps:
      - IN: x86-64-trigger
      - IN: windows-server-2016-trigger
      - TASK:
          name: multiple-cmd-should-not-work
          runtime:
            options:
              imageName: "microsoft/windowsservercore"
              imageTag: "10.0.14393.1884"
          script:
            - echo "next command will throw error"
            - cat x
            - echo "this command should not even be executed"

  - name: x86-64-windows-server-2016-container-custom-img-exit-cmd
    type: runSh
    runtime:
      architecture: x86_64
      cluster: x8664win2016custom
      container: true
    flags:
      - x86-64
      - windows-server-2016
      - windows-server-2016-custom-img
    steps:
      - IN: x86-64-trigger
      - IN: windows-server-2016-trigger
      - TASK:
          name: multiple-cmd-should-not-work
          runtime:
            options:
              imageName: "microsoft/windowsservercore"
              imageTag: "10.0.14393.1884"
          script:
            - echo "next command will be exit"
            - exit 1
            - echo "this command should not even be executed"

  - name: x86-64-windows-server-2016-container-custom-img-multitask-multiple-valid
    type: runSh
    runtime:
      architecture: x86_64
      cluster: x8664win2016custom
      container: true
    flags:
      - x86-64
      - windows-server-2016
      - windows-server-2016-custom-img
    steps:
      - IN: x86-64-trigger
      - IN: windows-server-2016-trigger
      - TASK:
          name: say-hi
          runtime:
            options:
              imageName: "microsoft/windowsservercore"
              imageTag: "10.0.14393.1884"
          script:
            - echo "hi 1"
            - echo "hi 2"
      - TASK:
          name: say-hello
          runtime:
            options:
              imageName: "microsoft/windowsservercore"
              imageTag: "10.0.14393.1884"
          script:
            - echo "hello 1"
            - echo "hello 2"

  - name: x86-64-windows-server-2016-container-custom-img-on-success
    type: runSh
    runtime:
      architecture: x86_64
      cluster: x8664win2016custom
      container: true
    flags:
      - x86-64
      - windows-server-2016
      - windows-server-2016-custom-img
    steps:
      - IN: x86-64-trigger
      - IN: windows-server-2016-trigger
      - TASK:
          name: on-success-should-work
          runtime:
            options:
              imageName: "microsoft/windowsservercore"
              imageTag: "10.0.14393.1884"
          script:
            - dir
    on_success:
      - script: echo "this should be logged"

  - name: x86-64-windows-server-2016-container-custom-img-on-failure
    type: runSh
    runtime:
      architecture: x86_64
      cluster: x8664win2016custom
      container: true
    flags:
      - x86-64
      - windows-server-2016
      - windows-server-2016-custom-img
    steps:
      - IN: x86-64-trigger
      - IN: windows-server-2016-trigger
      - TASK:
          name: on-failure-should-work
          runtime:
            options:
              imageName: "microsoft/windowsservercore"
              imageTag: "10.0.14393.1884"
          script:
            - invalidCommand
    on_failure:
      - script: echo "this should be logged"

  - name: x86-64-windows-server-2016-container-custom-img-on-success-always
    type: runSh
    runtime:
      architecture: x86_64
      cluster: x8664win2016custom
      container: true
    flags:
      - x86-64
      - windows-server-2016
      - windows-server-2016-custom-img
    steps:
      - IN: x86-64-trigger
      - IN: windows-server-2016-trigger
      - TASK:
          name: on-success-always-should-work
          runtime:
            options:
              imageName: "microsoft/windowsservercore"
              imageTag: "10.0.14393.1884"
          script:
            - dir
    on_success:
      - script: echo "this should be logged"
    always:
      - script: echo "this is always script"

  - name: x86-64-windows-server-2016-container-custom-img-on-failure-always
    type: runSh
    runtime:
      architecture: x86_64
      cluster: x8664win2016custom
      container: true
    flags:
      - x86-64
      - windows-server-2016
      - windows-server-2016-custom-img
    steps:
      - IN: x86-64-trigger
      - IN: windows-server-2016-trigger
      - TASK:
          name: on-failure-always-should-work
          runtime:
            options:
              imageName: "microsoft/windowsservercore"
              imageTag: "10.0.14393.1884"
          script:
            - invalidCommand
    on_failure:
      - script: echo "this should be logged"
    always:
      - script: echo "this is always script"
