jobs:
  - name: aarch64-host-in-out-process-in
    type: runSh
    runtime:
      architecture: aarch64
      os: Ubuntu_16.04
      container: false
    steps:
      - IN: aarch64-host-in-out-trigger
      - IN: aarch64-host-in-out-gitRepo
      - TASK:
          name: should-pass-with-gitRepo-envs
          runtime:
            options:
              env:
                HELLO: world
          script:
            - docker ps -a
            - printenv
            - test "$AARCH64HOSTINOUTGITREPO_BRANCH" == "aarch64-host-in-out"

  - name: aarch64-host-in-out-process-out
    type: runSh
    runtime:
      architecture: aarch64
      os: Ubuntu_16.04
      container: false
    steps:
      - IN: aarch64-host-in-out-trigger
      - OUT: aarch64-host-in-out-image
      - TASK:
          name: should-pass-with-image-envs
          runtime:
            options:
              env:
                HELLO: world
          script:
            - docker ps -a
            - printenv
            - echo "versionName=master.$BUILD_NUMBER" >> $JOB_STATE/aarch64-host-in-out-image.env
            - test "$AARCH64HOSTINOUTIMAGE_NAME" == "aarch64-host-in-out-image"
