jobs:
  - name: aarch64-new-yml-def-container
    type: runSh
    runtime:
      architecture: aarch64
      os: Ubuntu_16.04
      container: true
    steps:
      - IN: ci-gitRepo
      - TASK:
          name: system-facts
          script: 
            - uname -m
            - ps aux

  - name: old-min-sh
    type: runSh
    steps:
      - TASK:
        - script: echo "hello world"

  - name: new-min-sh
    type: runSh
    runtime:
      architecture: x86_64
      os: Ubuntu_16.04
      container: false
    steps:
      - TASK:
          name: echo-facts
          script: 
            - echo "cats are cute"
            - printenv
            # - ssh ubuntu@52.41.122.70 cat get-docker.sh

  - name: rc-ci_runCI
    type: runCI
    steps:
      - IN: ci-params
      - IN: ci-gitRepo
