jobs:
  - name: x86-64-ubuntu-16-04-host-envs-single
    type: runSh
    runtime:
      architecture: x86_64
      os: Ubuntu_16.04
      container: false
    flags:
      - x86-64
      - ubuntu-16-04
      - x86-64-ubuntu-16-04-host-envs
    steps:
      - IN: x86-64-trigger
      - IN: ubuntu-16-04-trigger
      - TASK:
          name: should-pass-for-single-envs
          runtime:
            options:
              env:
                HELLO: world
          script:
            - printenv
            - test "$HELLO" == "world"

  - name: x86-64-ubuntu-16-04-host-envs-multiple
    type: runSh
    runtime:
      architecture: x86_64
      os: Ubuntu_16.04
      container: false
    flags:
      - x86-64
      - ubuntu-16-04
      - x86-64-ubuntu-16-04-host-envs
    steps:
      - IN: x86-64-trigger
      - IN: ubuntu-16-04-trigger
      - TASK:
          name: should-pass-for-multiple-envs
          runtime:
            options:
              env:
                HELLO: world
                HI: there
          script:
            - printenv
            - test "$HELLO" == "world"
            - test "$HI" == "there"

  - name: x86-64-ubuntu-16-04-host-envs-inbuilt
    type: runSh
    runtime:
      architecture: x86_64
      os: Ubuntu_16.04
      container: false
    flags:
      - x86-64
      - ubuntu-16-04
      - x86-64-ubuntu-16-04-host-envs
    steps:
      - IN: x86-64-trigger
      - IN: ubuntu-16-04-trigger
      - TASK:
          name: should-have-inbuilt-envs
          script:
            - printenv
            - test "$SHIPPABLE_NODE_ARCHITECTURE" == "x86_64"
            - test "$SHIPPABLE_NODE_OPERATING_SYSTEM" == "Ubuntu_16.04"
            - test "$TASK_NAME" == "should-have-inbuilt-envs"
            - test "$TASK_IN_CONTAINER" == "false"

  - name: x86-64-ubuntu-16-04-host-envs-in-gitRepo
    type: runSh
    runtime:
      architecture: x86_64
      os: Ubuntu_16.04
      container: false
    flags:
      - x86-64
      - ubuntu-16-04
      - x86-64-ubuntu-16-04-host-envs
    steps:
      - IN: x86-64-trigger
      - IN: ubuntu-16-04-trigger
      - IN: master-gitRepo
      - TASK:
          name: should-have-gitRepo-envs
          script:
            - printenv
            - test "$MASTERGITREPO_BRANCH" == "master"
            - test "$MASTERGITREPO_OPERATION" == "IN"
