jobs:
  - name: x86-64-ubuntu-16-04-host-envs-single
    type: runSh
    runtime:
      architecture: x86_64
      os: Ubuntu_16.04
      container: false
    flags:
      - x86-64
      - ubuntu-16-04
      - x86-64-ubuntu-16-04-host-envs
    steps:
      - IN: x86-64-trigger
      - IN: ubuntu-16-04-trigger
      - TASK:
          name: should-pass-for-single-envs
          runtime:
            options:
              env:
                HELLO: world
          script:
            - printenv
            - echo "$HELLO"
            - test "$HELLO" == "world"
            
  - name: aarch64-host-envs-multiple
    type: runSh
    runtime:
      architecture: x86_64
      os: Ubuntu_16.04
      container: false
    flags:
      - x86-64
      - ubuntu-16-04
      - x86-64-ubuntu-16-04-host-envs
    steps:
      - IN: x86-64-trigger
      - IN: ubuntu-16-04-trigger
      - TASK:
          name: should-pass-for-multiple-envs
          runtime:
            options:
              env:
                HELLO: world
                HI: there
          script:
            - docker ps -a
            - printenv
            - echo "$HELLO"
            - test "$HELLO" == "world"
            - test "$HI" == "there"
