jobs:
  - name: x86-64-ubuntu-16-04-container-shipctl-get-integration-resource-keys
    type: runSh
    runtime:
      architecture: x86_64
      nodePool: x8664u16custom
      container: true
    flags:
      - x86-64
      - ubuntu-16-04
      - x86-64-ubuntu-16-04-container-shipctl
    steps:
      - IN: x86-64-trigger
      - IN: windows-server-2016-trigger
      - IN: checking-do-integration
      - IN: master-cluster
      - TASK:
          name: check-digital-ocean-integration
          script:
            - printenv
            - shipctl get_integration_resource_keys checking-do-integration
      - TASK:
          name: check-aws-integration-in-cluster
          script:
            - printenv
            - shipctl get_integration_resource_keys master-cluster
