jobs:
  
  - name: aarch64-old-yml-min
    type: runSh
    runtime:
      architecture: x86_64
      os: Ubuntu_16.04
      container: true
    steps:
      - TASK:
        - script: echo "hi"
        - script: echo "hello"
