jobs:
  - name: aarch64-ubuntu-16-04-container-shipctl
    type: runSh
    runtime:
      architecture: aarch64
      cluster: x8664u16custom
      container: true
    flags:
      - aarch64
      - ubuntu-16-04
    steps:
      - IN: aarch64-trigger
      - IN: ubuntu-16-04-trigger
      - TASK:
          name: shipctl-should-work
          script:
            - export OS_VERSION=$(lsb_release -a | head -3 | tail -1 | awk '{print $2}')
            - test "$OS_VERSION" == "16.04"
            - shipctl retry echo "it works"
