jobs:
  - name: x86-64-ubuntu-14-04-dynamic-host-shipctl
    type: runSh
    runtime:
      nodePool: x8664u14dynamic
      container: false
    flags:
      - x86-64
      - ubuntu-16-04
      - dynamic
      - shipctl
    steps:
      - TASK:
          name: intro-important-variables
          script:
            - printenv
            - ls -la /var/lib/shippable
            - ls -la /var/lib/shippable/build
            - echo "$JOB_STATE"
            - ls -la "$JOB_STATE"
