jobs:
  - name: x86-64-windows-server-2016-host-basic
    type: runSh
    runtime:
      architecture: x86_64
      os: WindowsServer_2016
      container: false
    flags:
      - x86-64
      - ubuntu-16-04
    steps:
      - IN: x86-64-trigger
      - TASK:
          name: shipctl-should-work
          script:
            - dir
