jobs:
  - name: x86-64-windows-server-2016-host-basic-single-valid
    type: runSh
    runtime:
      architecture: x86_64
      os: WindowsServer_2016
      container: false
    flags:
      - x86-64
      - windows-server-2016
    steps:
      - IN: x86-64-trigger
      - IN: windows-server-2016-trigger
      - TASK:
          name: single-cmd-should-work
          script:
            - dir
            
  - name: x86-64-windows-server-2016-host-basic-single-invalid
    type: runSh
    runtime:
      architecture: x86_64
      os: WindowsServer_2016
      container: false
    flags:
      - x86-64
      - windows-server-2016
    steps:
      - IN: x86-64-trigger
      - IN: windows-server-2016-trigger
      - TASK:
          name: single-cmd-should-not-work
          script:
            - invalidCommand

  - name: x86-64-windows-server-2016-host-basic-multiple-valid
    type: runSh
    runtime:
      architecture: x86_64
      os: WindowsServer_2016
      container: false
    flags:
      - x86-64
      - windows-server-2016
    steps:
      - IN: x86-64-trigger
      - IN: windows-server-2016-trigger
      - TASK:
          name: multiple-cmd-should-work
          script:
            - dir
            - echo "hello world"
            
  - name: x86-64-windows-server-2016-host-basic-multiple-invalid
    type: runSh
    runtime:
      architecture: x86_64
      os: WindowsServer_2016
      container: false
    flags:
      - x86-64
      - windows-server-2016
    steps:
      - IN: x86-64-trigger
      - IN: windows-server-2016-trigger
      - TASK:
          name: multiple-cmd-should-not-work
          script:
            - echo "next command will be invalid"
            - invalidCommand

  - name: x86-64-windows-server-2016-host-basic-multiple-error
    type: runSh
    runtime:
      architecture: x86_64
      os: WindowsServer_2016
      container: false
    flags:
      - x86-64
      - windows-server-2016
    steps:
      - IN: x86-64-trigger
      - IN: windows-server-2016-trigger
      - TASK:
          name: multiple-cmd-should-not-work
          script:
            - echo "next command will throw error"
            - cat x
            - echo "this command should not even be executed"
            
  - name: x86-64-windows-server-2016-host-basic-exit-cmd
    type: runSh
    runtime:
      architecture: x86_64
      os: WindowsServer_2016
      container: false
    flags:
      - x86-64
      - windows-server-2016
    steps:
      - IN: x86-64-trigger
      - IN: windows-server-2016-trigger
      - TASK:
          name: multiple-cmd-should-not-work
          script:
            - echo "next command will be exit"
            - exit 1
            - echo "this command should not even be executed"

  - name: x86-64-windows-server-2016-host-multitask-multiple-valid
    type: runSh
    runtime:
      architecture: x86_64
      os: WindowsServer_2016
      container: false
    flags:
      - x86-64
      - windows-server-2016
    steps:
      - IN: x86-64-trigger
      - IN: windows-server-2016-trigger
      - TASK:
          name: say-hi
          script:
            - echo "hi 1"
            - echo "hi 2"
      - TASK:
          name: say-hello
          script:
            - echo "hello 1"
            - echo "hello 2"
            
  - name: x86-64-windows-server-2016-host-basic-on-success
    type: runSh
    runtime:
      architecture: x86_64
      os: WindowsServer_2016
      container: false
    flags:
      - x86-64
      - windows-server-2016
    steps:
      - IN: x86-64-trigger
      - IN: windows-server-2016-trigger
      - TASK:
          name: shipctl-should-work
          script:
            - dir
    on_success:
      - script: echo "this should be logged"
      
  - name: x86-64-windows-server-2016-host-basic-on-failure
    type: runSh
    runtime:
      architecture: x86_64
      os: WindowsServer_2016
      container: false
    flags:
      - x86-64
      - windows-server-2016
    steps:
      - IN: x86-64-trigger
      - IN: windows-server-2016-trigger
      - TASK:
          name: shipctl-should-work
          script:
            - invalidCommand
    on_failure:
      - script: echo "this should be logged"
