jobs:
  - name: x86-64-macos-10-12-host-shipctl
    type: runSh
    runtime:
      architecture: x86_64
      os: macOS_10.12
      container: false
    flags:
      - x86-64
      - macos-10-12
    steps:
      - IN: x86-64-trigger
      - IN: macos-10-12-trigger
      - TASK:
          name: shipctl-should-work
          script: 
            - shipctl retry echo "it works"

  - name: x86-64-macos-10-12-host-aws-cli
    type: runSh
    runtime:
      architecture: x86_64
      os: macOS_10.12
      container: false
    flags:
      - x86-64
      - macos-10-12
    steps:
      - IN: macos-10-12-trigger
      - IN: x86-64-trigger
      - IN: test-aws-cli
      - TASK:
          name: should-list-ec2-instances
          script:
            - export MACOS_VERSION=$(sw_vers | head -2 | tail -1 | awk '{print $2}')
            - test "$MACOS_VERSION" == "10.12.6"
            - echo "$PATH"
            - aws ec2 describe-instances
            
  - name: x86-64-macos-10-12-host-gcloud-cli
    type: runSh
    runtime:
      architecture: x86_64
      os: macOS_10.12
      container: false
    flags:
      - x86-64
      - macos-10-12
    steps:
      - IN: macos-10-12-trigger
      - IN: x86-64-trigger
      - IN: test-gcloud-cli
      - TASK:
          name: should-list-gcloud-instances
          script:
            - export MACOS_VERSION=$(sw_vers | head -2 | tail -1 | awk '{print $2}')
            - test "$MACOS_VERSION" == "10.12.6"
            - gcloud compute instances list
            
  - name: x86-64-macos-10-12-host-azure-cli
    type: runSh
    runtime:
      architecture: x86_64
      os: macOS_10.12
      container: false
    flags:
      - x86-64
      - macos-10-12
    steps:
      - IN: macos-10-12-trigger
      - IN: x86-64-trigger
      - IN: test-azure-cli
      - TASK:
          name: should-list-azure-instances
          script:
            - export MACOS_VERSION=$(sw_vers | head -2 | tail -1 | awk '{print $2}')
            - test "$MACOS_VERSION" == "10.12.6"
            - az vm list 

  - name: x86-64-macos-10-12-host-docker-registry
    type: runSh
    runtime:
      architecture: x86_64
      os: macOS_10.12
      container: false
    flags:
      - x86-64
      - macos-10-12
    steps:
      - IN: macos-10-12-trigger
      - IN: x86-64-trigger
      - IN: test-docker-cli
      - TASK:
          name: should-pull-private-image
          script:
            - export MACOS_VERSION=$(sw_vers | head -2 | tail -1 | awk '{print $2}')
            - test "$MACOS_VERSION" == "10.12.6"
            - docker pull vishnushippable/private:nginx
      - TASK:
          name: should-build-private-image
          script:
            - export MACOS_VERSION=$(sw_vers | head -2 | tail -1 | awk '{print $2}')
            - test "$MACOS_VERSION" == "10.12.6"
            - mkdir private
            - pushd private
            - printf "FROM vishnushippable/private:nginx \nRUN touch hi" > Dockerfile
            - cat Dockerfile 
            - docker build -t="vishnushippable/private:nginx.$BUILD_NUMBER" .
            - popd
      - TASK:
          name: should-push-private-image
          script:
            - export MACOS_VERSION=$(sw_vers | head -2 | tail -1 | awk '{print $2}')
            - test "$MACOS_VERSION" == "10.12.6"
            - docker push vishnushippable/private:nginx.$BUILD_NUMBER
            

  - name: x86-64-macos-10-12-host-quay-registry
    type: runSh
    runtime:
      architecture: x86_64
      os: macOS_10.12
      container: false
    flags:
      - x86-64
      - macos-10-12
    steps:
      - IN: macos-10-12-trigger
      - IN: x86-64-trigger
      - IN: test-quay-cli
      - TASK:
          name: should-pull-private-image
          script:
            - export MACOS_VERSION=$(sw_vers | head -2 | tail -1 | awk '{print $2}')
            - test "$MACOS_VERSION" == "10.12.6"
            - docker pull quay.io/shippablequay/sample_node_01:nginx
      - TASK:
          name: should-build-private-image
          script:
            - export MACOS_VERSION=$(sw_vers | head -2 | tail -1 | awk '{print $2}')
            - test "$MACOS_VERSION" == "10.12.6"
            - mkdir private
            - pushd private
            - printf "FROM quay.io/shippablequay/sample_node_01:nginx \nRUN touch hi" > Dockerfile
            - cat Dockerfile 
            - docker build -t="quay.io/shippablequay/sample_node_01:nginx.$BUILD_NUMBER" .
            - popd
      - TASK:
          name: should-push-private-image
          script:
            - export MACOS_VERSION=$(sw_vers | head -2 | tail -1 | awk '{print $2}')
            - test "$MACOS_VERSION" == "10.12.6"
            - docker push quay.io/shippablequay/sample_node_01:nginx.$BUILD_NUMBER
