jobs:
  - name: x86-64-macos-10-12-host-shipctl
    type: runSh
    runtime:
      architecture: x86_64
      os: macOS_10.12
      container: false
    flags:
      - x86-64
      - macos-10-12
    steps:
      - IN: x86-64-trigger
      - IN: macos-10-12-trigger
      - TASK:
          name: shipctl-should-work
          script: 
            - shipctl retry echo "it works"

  - name: x86-64-macos-10-12-host-aws-cli
    type: runSh
    runtime:
      architecture: x86_64
      os: macOS_10.12
      container: false
    flags:
      - x86-64
      - macos-10-12
    steps:
      - IN: macos-10-12-trigger
      - IN: x86-64-trigger
      - IN: test-aws-cli
      - TASK:
          name: should-list-ec2-instances
          script:
            - export MACOS_VERSION=$(sw_vers | head -2 | tail -1 | awk '{print $2}')
            - test "$MACOS_VERSION" == "10.12.6"
            - echo "$PATH"
            - aws ec2 describe-instances
            

  - name: x86-64-macos-10-12-host-docker-registry
    type: runSh
    runtime:
      architecture: x86_64
      os: macOS_10.12
      container: false
    flags:
      - x86-64
      - macos-10-12
    steps:
      - IN: macos-10-12-trigger
      - IN: x86-64-trigger
      - IN: test-docker-cli
      - TASK:
          name: should-pull-private-image
          script:
            - export MACOS_VERSION=$(sw_vers | head -2 | tail -1 | awk '{print $2}')
            - test "$MACOS_VERSION" == "10.12.6"
            - docker pull vishnushippable/private:nginx
      - TASK:
          name: should-build-private-image
          script:
            - export MACOS_VERSION=$(sw_vers | head -2 | tail -1 | awk '{print $2}')
            - test "$MACOS_VERSION" == "10.12.6"
            - mkdir private
            - pwd
            - pushd private
            - pwd
            - ls
            - echo "FROM vishnushippable/private:nginx
              RUN touch hi
              " > Dockerfile
            - cat Dockerfile 
            - ls
            - popd
