jobs:
  - name: x86-64-macos-10-12-host-aws-cli
    type: runSh
    runtime:
      architecture: x86_64
      os: macOS_10.12
      container: false
    flags:
      - macos-10-12
      - x86-64
    steps:
      - IN: macos-10-12-trigger
      - IN: x86-64-trigger
      - IN: test-aws-cli
      - TASK:
          name: should-pass-with-gitRepo-envs
          script:
            - export MACOS_VERSION=$(sw_vers | head -2 | tail -1 | awk '{print $2}')
            - test "$MACOS_VERSION" == "10.12.6"
            - aws ec2 describe-instances
