jobs:

  - name: aarch64-host-ssh-basic
    type: runSh
    runtime:
      architecture: aarch64
      os: Ubuntu_16.04
      container: false
    steps:
      - IN: aarch64-host-ssh-trigger
      - TASK:
          name: should-ssh
          script: 
            - ssh ubuntu@35.166.229.98 -c echo "hello" # or cat something
