jobs:

  - name: aarch64-host-ssh-basic
    type: runSh
    runtime:
      architecture: aarch64
      cluster: x8664u16custom
      container: false
    steps:
      - IN: aarch64-host-ssh-trigger
      - TASK:
          name: should-ssh
          script: 
            - ssh -o StrictHostKeyChecking=no -v ubuntu@35.166.229.98 echo "hello" # or cat something
