jobs:

  - name: aarch64-host-new-yml-basic
    type: runSh
    runtime:
      architecture: aarch64
      os: Ubuntu_16.04
      container: false
    steps:
      - IN: heap-1635-trigger
      - TASK:
          name: echo-facts
          script: 
            - uname -m
            - ps aux

  - name: aarch64-host-new-yml-fail
    type: runSh
    runtime:
      architecture: aarch64
      os: Ubuntu_16.04
      container: false
    steps:
      - IN: heap-1635-trigger
      - TASK:
          name: echo-facts
          script: 
            - exit 1

  - name: aarch64-host-new-yml-multi-task
    type: runSh
    runtime:
      architecture: aarch64
      os: Ubuntu_16.04
      container: false
    steps:
      - IN: heap-1635-trigger
      - TASK:
          name: echo-facts
          script: 
            - uname -m
      - TASK:
          name: ps-facts
          script:
            - ps aux
            
  - name: aarch64-host-new-yml-mix-container
    type: runSh
    steps:
      - IN: heap-1635-trigger
      - TASK:
          name: echo-facts
          runtime:
            architecture: aarch64
            os: Ubuntu_16.04
            container: true
            options:
              imageName: drydockaarch64/u16pyt
              imageTag: master
          script: 
            - uname -m
      - TASK:
          name: ps-facts
          script:
            - ps aux

