jobs:
  - name: x86-64-ubuntu-16-04-container-envs-single
    type: runSh
    runtime:
      architecture: x86_64
      nodePool: x8664u16custom
      container: true
    flags:
      - x86-64
      - ubuntu-16-04
      - x86-64-ubuntu-16-04-container-envs
    steps:
      - IN: x86-64-trigger
      - IN: ubuntu-16-04-trigger
      - TASK:
          name: should-pass-for-single-envs
          runtime:
            options:
              env:
                HELLO: world
          script:
            - printenv
            - test "$HELLO" == "world"
            - sleep 1m
            - echo "This should not show up if job was cancelled"

  - name: x86-64-ubuntu-16-04-container-envs-single-break
    type: runSh
    runtime:
      architecture: x86_64
      nodePool: x8664u16custom
      container: true
    flags:
      - x86-64
      - ubuntu-16-04
      - x86-64-ubuntu-16-04-container-envs
    steps:
      - IN: x86-64-trigger
      - IN: ubuntu-16-04-trigger
      - TASK:
          name: should-pass-for-single-envs
          runtime:
            options:
              env:
                HELLO: "this contains a \" special character"
          script:
            - printenv

  - name: x86-64-ubuntu-16-04-container-envs-multiple
    type: runSh
    runtime:
      architecture: x86_64
      nodePool: x8664u16custom
      container: true
    flags:
      - x86-64
      - ubuntu-16-04
      - x86-64-ubuntu-16-04-container-envs
    steps:
      - IN: x86-64-trigger
      - IN: ubuntu-16-04-trigger
      - TASK:
          name: should-pass-for-multiple-envs
          runtime:
            options:
              env:
                HELLO: world
                HI: there
          script:
            - printenv
            - test "$HELLO" == "world"
            - test "$HI" == "there"

  - name: x86-64-ubuntu-16-04-container-envs-inbuilt
    type: runSh
    runtime:
      architecture: x86_64
      nodePool: x8664u16custom
      container: true
    flags:
      - x86-64
      - ubuntu-16-04
      - x86-64-ubuntu-16-04-container-envs
    steps:
      - IN: x86-64-trigger
      - IN: ubuntu-16-04-trigger
      - TASK:
          name: should-have-inbuilt-envs
          script:
            - printenv
            - test "$SHIPPABLE_NODE_ARCHITECTURE" == "x86_64"
            - test "$SHIPPABLE_NODE_OPERATING_SYSTEM" == "Ubuntu_16.04"
            - test "$TASK_NAME" == "should-have-inbuilt-envs"
            - test "$TASK_IN_CONTAINER" == "true"

  - name: x86-64-ubuntu-16-04-container-envs-in-gitRepo
    type: runSh
    runtime:
      architecture: x86_64
      nodePool: x8664u16custom
      container: true
    flags:
      - x86-64
      - ubuntu-16-04
      - x86-64-ubuntu-16-04-container-envs
    steps:
      - IN: x86-64-trigger
      - IN: ubuntu-16-04-trigger
      - IN: master-gitRepo
      - TASK:
          name: should-have-gitRepo-envs
          script:
            - printenv
            - test "$MASTERGITREPO_BRANCH" == "master"
            - test "$MASTERGITREPO_OPERATION" == "IN"

  - name: x86-64-ubuntu-16-04-container-envs-in-param
    type: runSh
    runtime:
      architecture: x86_64
      nodePool: x8664u16custom
      container: true
    flags:
      - x86-64
      - ubuntu-16-04
      - x86-64-ubuntu-16-04-container-envs
    steps:
      - IN: x86-64-trigger
      - IN: ubuntu-16-04-trigger
      - IN: master-params
      - TASK:
          name: should-have-param-envs
          script:
            - printenv
            - test "$KEY1" == "value1"
            - test "$KEY2" == "value2"

  - name: x86-64-ubuntu-16-04-container-envs-out-image
    type: runSh
    runtime:
      architecture: x86_64
      nodePool: x8664u16custom
      container: true
    flags:
      - x86-64
      - ubuntu-16-04
      - x86-64-ubuntu-16-04-container-envs
    steps:
      - IN: x86-64-trigger
      - IN: ubuntu-16-04-trigger
      - OUT: master-image-1
      - TASK:
          name: should-have-image-envs
          script:
            - printenv
            - test "$MASTERIMAGE1_NAME" == "master-image-1"

  - name: x86-64-ubuntu-16-04-container-envs-integration
    type: runSh
    runtime:
      architecture: x86_64
      nodePool: x8664u16custom
      container: true
    flags:
      - x86-64
      - ubuntu-16-04
      - x86-64-ubuntu-16-04-container-envs
    steps:
      - IN: x86-64-trigger
      - IN: ubuntu-16-04-trigger
      - IN: checking-do-integration
      - IN: checking-key-value-pair
      - TASK:
          name: should-have-image-envs
          script:
            - printenv
            - test "$CHECKINGDOINTEGRATION_INTEGRATION_APITOKEN" == "not-really-an-api-token"

  - name: x86-64-ubuntu-16-04-container-envs-single-multiline
    type: runSh
    runtime:
      architecture: x86_64
      nodePool: x8664u16custom
      container: true
    flags:
      - x86-64
      - ubuntu-16-04
      - x86-64-ubuntu-16-04-container-envs
    steps:
      - IN: x86-64-trigger
      - IN: ubuntu-16-04-trigger
      - TASK:
          name: should-pass-for-multiline-envs
          runtime:
            options:
              env:
                HELLO: |
                  first line
                  second line
          script:
            - printenv
            - echo $HELLO

  - name: x86-64-ubuntu-16-04-container-envs-all-in
    type: runSh
    runtime:
      architecture: x86_64
      nodePool: x8664u16custom
      container: true
    flags:
      - x86-64
      - ubuntu-16-04
      - x86-64-ubuntu-16-04-container-envs
    steps:
      - IN: x86-64-trigger
      - IN: ubuntu-16-04-trigger
      - IN: master-cluster
      - IN: master-dockerOptions
      - IN: master-file
      - IN: master-gitRepo
      - IN: master-image-1
      - IN: checking-do-integration
      - IN: checking-ssh-integration
      - IN: master-params
      - IN: master-replicas
      - IN: master-trigger
      - IN: master-version
      - TASK:
          name: should-show-envs-for-all-INs
          script:
            - printenv
