jobs:

  - name: aarch64-opts-in-default-container-base-env
    type: runSh
    runtime:
      architecture: aarch64
      os: Ubuntu_16.04
      container: true
      options:
        env:
          HELLO: world
    steps:
      - IN: aarch64-default-container-trigger
      - TASK:
          name: system-facts
          script:
            - docker ps -a
            - printenv
            - echo "$HELLO"
            - test "$HELLO" == "world"
            

  - name: aarch64-opts-in-default-container-task-env
    type: runSh
    runtime:
      architecture: aarch64
      os: Ubuntu_16.04
      container: true
    steps:
      - IN: aarch64-default-container-trigger
      - TASK:
          name: system-facts
          runtime:
            options:
              env:
                HELLO: world
          script:
            - docker ps -a
            - printenv
            - echo "$HELLO"
            - test "$HELLO" == "world"

  - name: aarch64-opts-in-default-container-base-opts-mem
    type: runSh
    runtime:
      architecture: aarch64
      os: Ubuntu_16.04
      container: true
      options:
        options: -m 300m
    steps:
      - IN: aarch64-default-container-trigger
      - TASK:
          name: should-have-right-memory
          script:
            - docker ps -a
            
  - name: aarch64-opts-in-default-container-task-opts-mem
    type: runSh
    runtime:
      architecture: aarch64
      os: Ubuntu_16.04
      container: true
    steps:
      - IN: aarch64-default-container-trigger
      - TASK:
          name: should-have-right-memory
          runtime:
            options:
              options: -m 300m
          script:
            - docker ps -a
            - docker inspect reqExec.$BUILD_JOB_ID.0
            - export MEM=$(docker inspect --format='{{.HostConfig.Memory}}' reqExec.$BUILD_JOB_ID.0)
            - test "$MEM" -eq 314572800

